name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env: 
          POSTGRES_USER: env.POSTGRES_USER
          POSTGRES_PASSWORD: env.POSTGRES_PASSWORD
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golang-migrate
      run:  |
        sudo curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add - 
        sudo echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
        sudo apt-get update
        sudo apt-get install -y migrate

    - name: Run migrations
      run: make migrateup

    - name: Update dependencies
      run: go mod tidy

    - name: Unit Testing
      run: make test