name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env: 
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golang-migrate
      run:  |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin

    - name: Run migrations
      run: migrate -path infra/db/migration -database "${{ secrets.POSTGRES_CONN_URL }}" -verbose up

    - name: Update dependencies
      run: go mod tidy

    - name: Create .env file
      run: |
        sudo echo "${{ secrets.DB_USER }}" > /.env
        sudo echo "${{ secrets.DB_PASS }}" >> /.env
        sudo echo "${{ secrets.DB_HOST }}" >> /.env
        sudo echo "${{ secrets.DB_PORT }}" >> /.env
        sudo echo "${{ secrets.DB_NAME }}" >> /.env
        sudo echo "${{ secrets.DB_DRIVER }}" >> /.env

    - name: Listing dir
      run: ls

    - name: Unit Testing
      run: make test